classdef NAAppraiser < handle
    % Class for the appraisal phase of the neighborhood algorithm
    %
    % Arguments: 
    % n_resample: int, the number of resamples to use for the appraisal.
    % n_walkers: int, the number of walkers to use in parallel.
    % searcher: NASearcher, search phase which may provide the initial
    %       ensemble, log_ppd, and bounds.
    % 
    % Properties: 
    % initial_ensemble: array, user-provided or generated by a NASearcher
    %       object.
    % log_ppd: array, the log posterior probability values for each sample.
    % bounds: array, set of tuples representing the bounds of the search
    %       space. Column 1 contains the lower bound and column 2 contains 
    %       the upper bound for each parameter.
    % nd: int, number of dimensions of the search space.
    % lower: column vector, lower bounds of the search space.
    % upper: column vector, upper bounds of the search space.
    % Cm: column vector, diagonal prior covariance matrix.
    % verbose: Boolean, whether to display the progress bar.
    % Ne: int, length of the initial ensemble.
    % j: int, number of walkers.
    % nr: int, number of cells to resample per walker (if in parallel). 
    % rngs: RandStream object, random number generator with nr-many streams.
    % mean: array, mean of the samples.
    % sample_mean_error: array, error of the mean. 
    % covariance: array, covariance of the samples.
    % sample_covariance_error: array, error of the covariance of the samples.
    % samples: array, samples generated by the appraisal.

    properties
        initial_ensemble
        log_ppd
        bounds
        nd
        lower
        upper
        Cm
        verbose = true
        Ne
        j
        nr
        rngs
        mean
        sample_mean_error
        covariance
        sample_covariance_error
        samples
    end

    methods
        function obj = NAAppraiser(n_resample, n_walkers, searcher, ...
                verbose, seed, initial_ensemble, log_ppd, bounds)
            % Constructor for the NAAppraiser class
            
            if nargin > 0
                if isa(searcher,'NASearcher')
                    initial_ensemble = searcher.samples;
                    log_ppd = searcher.objectives .* (-1);
                    bounds = searcher.bounds;
                    verbose = false;
                end
                if isempty(seed)
                    seed = 42;
                end
                obj.initial_ensemble = initial_ensemble;
                obj.log_ppd = log_ppd;
                obj.bounds = bounds;
                obj.nd = size(bounds, 1);
                obj.lower = bounds(:, 1);
                obj.upper = bounds(:, 2);
                obj.Cm = ((obj.upper - obj.lower).^(-2));
                obj.verbose = verbose;

                obj.Ne = size(initial_ensemble, 1);
                obj.nr = floorDiv(n_resample, n_walkers);
                if n_walkers >= 1
                    obj.j = n_walkers;
                else
                    obj.j = 1;
                end
                obj.rngs = RandStream.create("mrg32k3a", ...
                    "NumStreams", (obj.nr*obj.nd), "Seed", seed);
            end
        end

        function run(obj, save, start_fraction)
            % Runs the appraisal phase 
            
            if obj.j == 1
                accumulator = obj.run_serial(save);
            else
                if start_fraction < 0 || start_fraction > 1
                    error("start_fraction must be between 0 and 1");
                end
                accumulator = obj.run_parallel(save, start_fraction);
            end

            obj.mean = accumulator.mean();
            obj.sample_mean_error = accumulator.sample_mean_error();
            obj.covariance = accumulator.covariance();
            obj.sample_covariance_error = accumulator.sample_covariance_error();
            if save & size(accumulator.samples) ~= 0
                obj.samples = accumulator.samples;
            end
        end

        function accumulator = run_serial(obj, save)
            % Runs the serial version of the appraisal phase 
            
            if nargin < 1
                save = true;
            end
            
            [~, start] = max(obj.log_ppd);
            accumulator = MCIntegrals(obj.nd, save);
            xA = obj.random_walk_through_parameter_space(1, start);
            for i = 1:size(xA, 1)
                accumulator.accumulate(xA(i, :));
            end
        end

        function accumulator = run_parallel(obj, save, start_fraction)
            % Runs the parallel version of the appraisal phase 
            
            if nargin < 2
                save = true;
                start_fraction = 0.5;            
            elseif nargin < 1
                save = true;
            end
            
            % Select start points for random walks 
            % Taken from the best start_fraction*100% of cells to avoid
            % walking in low probability regions
            int_threshold = int16(obj.Ne * start_fraction);
            [~, largest_log_ppd] = maxk(obj.log_ppd, int_threshold);
            start_points = largest_log_ppd(randperm(numel(largest_log_ppd), obj.j));
            
            % Ensure at least one walker starts at the best cell
            [~, start] = max(obj.log_ppd);
            start_points(1) = start;

            % accumulators = createArray(obj.j, 1, Like=MCIntegrals(obj.nd, save));
            accumulators = [];

            % in parallel, run appraise() on all combos of accumulators,
            % rngs, and start_points
            params = combinations(1:obj.j, 1:obj.nr);
            % need empty vector of length nr*#params
            % will initialize new MCI object in the loop, accumulate there
            % (check if MCI has updated)
            % add new MCI object to the list 
            % accumulate the MCIs in the list to the 
            for rng = 1:obj.nr
                for i = 1:size(params, 1)
                    acc = MCIntegrals(obj.nd, save);
                    k = params{i, 2};
                    obj.appraise(acc, rng, start_points(k)); 
                    accumulators = [accumulators; acc];
                end
            end

            % Combine the results
            accumulator = MCIntegrals(obj.nd, save);
            for i = 1:obj.j
                acc = accumulators(i);
                acc.samples
                accumulator.accumulate(acc);
            end
        end

        function accumulator = appraise(obj, accumulator, rng, start_k)
            % Performs a random walk through the search space, then
            % accumulates the resulting samples.
            
            xA = obj.random_walk_through_parameter_space(rng, start_k);
            for i = 1:size(xA, 1) 
                accumulator.accumulate(xA(i));
            end
        end

        function new_samples = random_walk_through_parameter_space(obj, rng, start_k)
            % Performs a random walk through the search space. Yields a new 
            % sample at each iteration to be used for calculating summary 
            % statistics.
            
            obj.rngs.Substream = rng;
            
            % Display progress bar
            if obj.verbose 
                wb = waitbar(0, "NAII - Random Walk");
            end

            new_samples = zeros(obj.nr, obj.nd);
            xA = obj.initial_ensemble(start_k, :);
            
            for iter = 1:obj.nr
                for i = 1:obj.nd
                    stream_num = (iter - 1) * obj.nd + i;
                    [intersections, cells] = obj.axis_intersections(i, xA);
                    xpi = obj.random_step(i, intersections, cells, stream_num);  
                    xA(i) = xpi;
                end
                new_samples(iter, :) = xA;
                if obj.verbose
                    waitbar(iter/obj.nr, wb, "NAII - Random Walk");
                end
            end
        end

        function [intersections, cells] = axis_intersections(obj, axis, xA)
            % Calculate the intersections of an axis passing through point 
            % vk in the kth cell with the boundaries of all cells. Returns 
            % the intersection points and the cells the axis passes through
            
            % d: component-wise squared distance to all other cells
            % d2: total scaled distance to all other cells
            % k: index of the nearest cell
            % dk2: perpendicular distance to axis
            
            d = (xA - obj.initial_ensemble).^2; % component-wise squared distance 
            d2 = d * obj.Cm; % total scaled distance to all 
            [~, k] = min(d2);
            d(:, axis) = []; % delete axis column in d
            temp2 = obj.Cm;
            temp2(axis) = []; % delete axis element in Cm
            dk2 = d * temp2;

            % Travel down the axis
            [down_intersections, down_cells] = obj.get_axis_intersections( ...
                axis, k, dk2, true, false);

            [up_intersections, up_cells] = obj.get_axis_intersections( ...
                axis, k, dk2, false, true);
            
            % reverse the order of the down intersections and cells so that 
            % the order of the intersections is from lowest to highest
            intersections = [flipud(down_intersections); up_intersections];
            cells = [flipud(down_cells); k; up_cells];
        end

        function xpi = random_step(obj, axis, intersections, cells, rng)
            % Takes a random step in the search space. Intersections are 
            % the points where the axis intersects the boundaries of the 
            % cells.
            
            obj.rngs.Substream = rng;
            while true
                xpi = rand(obj.rngs) * (obj.upper(axis) - obj.lower(axis) ...
                    ) + obj.lower(axis);
                k = obj.identify_cell(xpi, intersections, cells);
                
                r = rand(obj.rngs);
                logPxpi = obj.log_ppd(k);
                logPmax = max(obj.log_ppd(cells));
                
                % eqn (24) Sambridge 1999(II)
                if log(r) < logPxpi - logPmax
                    break;
                end
            end
        end

        function [intersections, cells] = get_axis_intersections(obj, axis, ...
                k, di2, down, up)
            % Returns the intersection points and the cells the axis passes
            % through. 
            
            assert(~(up & down));

            intersections = double.empty(0, 1);
            cells = double.empty(0, 1);

            % eqn (19) Sambridge 1999
            vk = obj.initial_ensemble(k, :);
            vki = vk(:, axis);
            vji = obj.initial_ensemble(:, axis);

            a = di2(k) - di2;
            b = obj.Cm(axis) .* (vki - vji);
            xji = 0.5 .* (vki + vji + a ./ b);
            xji_masked = xji;

            if down 
                mask = (vki <= vji) | ~isfinite(xji);
                mask_id = [find(mask==1)];
                xji_masked(mask_id) = -1e+20;
            else
                mask = (vki >= vji) | ~isfinite(xji);
                mask_id = [find(mask==1)];
                xji_masked(mask_id) = 1e+20;
            end

            if (length(mask) - sum(mask)) > 0 % valid intersection found
                if down
                    [~, k_new] = max(xji_masked);
                else
                    [~, k_new] = min(xji_masked);
                end

                intersections = [intersections; xji(k_new)];
                cells = [cells; k_new];
                    
                [new_intersections, new_cells] = obj.get_axis_intersections( ...
                    axis, k_new, di2, down, up);
                
                intersections = [intersections; new_intersections];
                cells = [cells; new_cells];
            end
        end

        function cell = identify_cell(~, xp, intersections, cells)
            % Given a set of intersections and the cells they pass through,
            % identify the cell that contains the point xp.

            [~, closest_intersection] = min(abs(intersections - xp));
            if xp < intersections(closest_intersection)
                cell_id = closest_intersection;
            else
                cell_id = closest_intersection + 1;
            end
            cell = cells(cell_id);
        end
    end
end